.TH CINNAMON-EXTENSION-TOOL 1 2012-07-23  Sagarmatha "sagarmatha manual"
.SH NAME
sagarmatha-extension-tool \- extension management program
.SH SYNOPSIS
.SY sagarmatha-extension-tool
.OP \-\-create-extension
.br
.SH DESCRIPTION
.LP
\fBsagarmatha-extension-tool\fP runs the graphical user interface allowing to
manage the extensions to be used in sagarmatha.
.SH "SEE ALSO"
.BR sagarmatha-settings (1)

