.TH SAGARMATHA-MENU-EDITOR 1 2012-07-23  Sagarmatha "sagarmatha manual"
.SH NAME
sagarmatha-menu-editor \- Editor for the panel menu
.SH SYNOPSIS
.SY sagarmatha-menu-editor
.SH DESCRIPTION
.LP
\fBsagarmatha-menu-editor\fP runs the graphical user interface allowing to
edit the menu displayed in sagarmatha.
.SH "SEE ALSO"
.BR sagarmatha-settings (1)

