.TH CINNAMON-LAUNCHER 1 2012-07-29  Sagarmatha "sagarmatha manual"
.SH NAME
sagarmatha-launcher \- Start or restart a sagarmatha session
.SH SYNOPSIS
.SY sagarmatha-launcher
.SH DESCRIPTION
.LP
\fBsagarmatha-launcher\fP runs the graphical user interface allowing to
start or restart a session of sagarmatha desktop.
.SH "SEE ALSO"
.BR sagarmatha (1)

