.TH SAGARMATHA-SETTINGS 1 2012-07-23  Sagarmatha "sagarmatha manual"
.SH NAME
sagarmatha-settings \- Configuration panel for sagarmatha
.SH SYNOPSIS
.SY sagarmatha-settings
.SH DESCRIPTION
.LP
\fBsagarmatha-settings\fP runs the graphical user interface allowing to
configure sagarmatha
.SH "SEE ALSO"
.BR sagarmatha-menu-editor (1)

